
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AiNextStepPanel: typeof import("../components/AiNextStepPanel.vue")['default']
export const ProseA: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.vue")['default']
export const ProseAccordion: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.vue")['default']
export const ProseAccordionItem: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.vue")['default']
export const ProseBadge: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.vue")['default']
export const ProseCallout: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.vue")['default']
export const ProseCard: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.vue")['default']
export const ProseCardGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.vue")['default']
export const ProseCode: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.vue")['default']
export const ProseCodeCollapse: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.vue")['default']
export const ProseCodeGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.vue")['default']
export const ProseCodeIcon: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.vue")['default']
export const ProseCodePreview: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.vue")['default']
export const ProseCollapsible: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.vue")['default']
export const ProseEm: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.vue")['default']
export const ProseField: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.vue")['default']
export const ProseFieldGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.vue")['default']
export const ProseH1: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.vue")['default']
export const ProseH2: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.vue")['default']
export const ProseH3: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.vue")['default']
export const ProseH4: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.vue")['default']
export const ProseH5: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.vue")['default']
export const ProseH6: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.vue")['default']
export const ProseHr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.vue")['default']
export const ProseImg: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.vue")['default']
export const ProseKbd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.vue")['default']
export const ProseLi: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.vue")['default']
export const ProseOl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.vue")['default']
export const ProseP: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.vue")['default']
export const ProsePre: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.vue")['default']
export const ProsePrompt: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Prompt.vue")['default']
export const ProseScript: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.vue")['default']
export const ProseSteps: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.vue")['default']
export const ProseStrong: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.vue")['default']
export const ProseTable: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.vue")['default']
export const ProseTabs: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.vue")['default']
export const ProseTabsItem: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.vue")['default']
export const ProseTbody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.vue")['default']
export const ProseTh: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.vue")['default']
export const ProseThead: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.vue")['default']
export const ProseTr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.vue")['default']
export const ProseUl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.vue")['default']
export const ProseCaution: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.vue")['default']
export const ProseNote: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.vue")['default']
export const ProseTip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.vue")['default']
export const ProseWarning: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.vue")['default']
export const B24Accordion: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']
export const B24Advice: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']
export const B24Alert: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']
export const B24App: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']
export const B24Avatar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']
export const B24AvatarGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']
export const B24Badge: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']
export const B24Banner: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.vue")['default']
export const B24Breadcrumb: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.vue")['default']
export const B24Button: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']
export const B24Calendar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']
export const B24Card: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.vue")['default']
export const B24ChatMessage: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatMessage.vue")['default']
export const B24ChatMessages: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatMessages.vue")['default']
export const B24ChatPalette: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPalette.vue")['default']
export const B24ChatPrompt: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPrompt.vue")['default']
export const B24ChatPromptSubmit: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPromptSubmit.vue")['default']
export const B24ChatReasoning: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatReasoning.vue")['default']
export const B24ChatShimmer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatShimmer.vue")['default']
export const B24ChatTool: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatTool.vue")['default']
export const B24Checkbox: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']
export const B24CheckboxGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.vue")['default']
export const B24Chip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']
export const B24Collapsible: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']
export const B24ColorPicker: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.vue")['default']
export const B24CommandPalette: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.vue")['default']
export const B24Container: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']
export const B24ContextMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.vue")['default']
export const B24ContextMenuContent: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.vue")['default']
export const B24Countdown: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']
export const B24DashboardGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.vue")['default']
export const B24DashboardNavbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardNavbar.vue")['default']
export const B24DashboardPanel: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardPanel.vue")['default']
export const B24DashboardResizeHandle: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardResizeHandle.vue")['default']
export const B24DashboardSearch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.vue")['default']
export const B24DashboardSearchButton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.vue")['default']
export const B24DashboardSidebar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebar.vue")['default']
export const B24DashboardSidebarCollapse: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebarCollapse.vue")['default']
export const B24DashboardSidebarToggle: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebarToggle.vue")['default']
export const B24DashboardToolbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardToolbar.vue")['default']
export const B24DescriptionList: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']
export const B24Drawer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Drawer.vue")['default']
export const B24DropdownMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']
export const B24DropdownMenuContent: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']
export const B24Editor: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Editor.vue")['default']
export const B24EditorDragHandle: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorDragHandle.vue")['default']
export const B24EditorEmojiMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorEmojiMenu.vue")['default']
export const B24EditorMentionMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorMentionMenu.vue")['default']
export const B24EditorSuggestionMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorSuggestionMenu.vue")['default']
export const B24EditorToolbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorToolbar.vue")['default']
export const B24Empty: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.vue")['default']
export const B24Error: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.vue")['default']
export const B24FieldGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.vue")['default']
export const B24FileUpload: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.vue")['default']
export const B24Footer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Footer.vue")['default']
export const B24FooterColumns: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FooterColumns.vue")['default']
export const B24Form: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']
export const B24FormField: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']
export const B24Header: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Header.vue")['default']
export const B24Input: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']
export const B24InputDate: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputDate.vue")['default']
export const B24InputMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']
export const B24InputNumber: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']
export const B24InputTags: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.vue")['default']
export const B24InputTime: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTime.vue")['default']
export const B24Kbd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']
export const B24Link: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']
export const B24LinkBase: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']
export const B24Main: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Main.vue")['default']
export const B24Modal: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']
export const B24ModalDialogClose: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']
export const B24Navbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']
export const B24NavbarDivider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']
export const B24NavbarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']
export const B24NavbarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']
export const B24NavigationMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']
export const B24OverlayProvider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']
export const B24Page: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Page.vue")['default']
export const B24PageAside: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageAside.vue")['default']
export const B24PageBody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageBody.vue")['default']
export const B24PageCard: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.vue")['default']
export const B24PageCardGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCardGroup.vue")['default']
export const B24PageColumns: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.vue")['default']
export const B24PageFeature: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageFeature.vue")['default']
export const B24PageGrid: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.vue")['default']
export const B24PageHeader: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageHeader.vue")['default']
export const B24PageLinks: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.vue")['default']
export const B24PageList: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.vue")['default']
export const B24PageSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageSection.vue")['default']
export const B24Pagination: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.vue")['default']
export const B24PinInput: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.vue")['default']
export const B24Popover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']
export const B24Progress: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']
export const B24RadioGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']
export const B24Range: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']
export const B24ScrollArea: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ScrollArea.vue")['default']
export const B24Select: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']
export const B24SelectMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']
export const B24Separator: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']
export const B24Sidebar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']
export const B24SidebarBody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']
export const B24SidebarFooter: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']
export const B24SidebarHeader: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']
export const B24SidebarHeading: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']
export const B24SidebarLayout: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']
export const B24SidebarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']
export const B24SidebarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']
export const B24Skeleton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']
export const B24Slideover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']
export const B24Stepper: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.vue")['default']
export const B24Switch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']
export const B24Table: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.vue")['default']
export const B24TableWrapper: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.vue")['default']
export const B24Tabs: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']
export const B24Textarea: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']
export const B24Theme: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Theme.vue")['default']
export const B24Timeline: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.vue")['default']
export const B24Toast: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']
export const B24Toaster: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']
export const B24Tooltip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']
export const B24User: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.vue")['default']
export const B24LocaleSelect: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAiNextStepPanel: LazyComponent<typeof import("../components/AiNextStepPanel.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.vue")['default']>
export const LazyProseAccordion: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.vue")['default']>
export const LazyProseAccordionItem: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.vue")['default']>
export const LazyProseBadge: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.vue")['default']>
export const LazyProseCallout: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.vue")['default']>
export const LazyProseCard: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.vue")['default']>
export const LazyProseCardGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.vue")['default']>
export const LazyProseCodeCollapse: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.vue")['default']>
export const LazyProseCodeGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.vue")['default']>
export const LazyProseCodeIcon: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.vue")['default']>
export const LazyProseCodePreview: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.vue")['default']>
export const LazyProseCollapsible: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.vue")['default']>
export const LazyProseField: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.vue")['default']>
export const LazyProseFieldGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.vue")['default']>
export const LazyProseKbd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.vue")['default']>
export const LazyProsePrompt: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Prompt.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.vue")['default']>
export const LazyProseSteps: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.vue")['default']>
export const LazyProseTabs: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.vue")['default']>
export const LazyProseTabsItem: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.vue")['default']>
export const LazyProseCaution: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.vue")['default']>
export const LazyProseNote: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.vue")['default']>
export const LazyProseTip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.vue")['default']>
export const LazyProseWarning: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.vue")['default']>
export const LazyB24Accordion: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']>
export const LazyB24Advice: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']>
export const LazyB24Alert: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']>
export const LazyB24App: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']>
export const LazyB24Avatar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']>
export const LazyB24AvatarGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']>
export const LazyB24Badge: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']>
export const LazyB24Banner: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.vue")['default']>
export const LazyB24Breadcrumb: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.vue")['default']>
export const LazyB24Button: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']>
export const LazyB24Calendar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']>
export const LazyB24Card: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.vue")['default']>
export const LazyB24ChatMessage: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatMessage.vue")['default']>
export const LazyB24ChatMessages: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatMessages.vue")['default']>
export const LazyB24ChatPalette: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPalette.vue")['default']>
export const LazyB24ChatPrompt: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPrompt.vue")['default']>
export const LazyB24ChatPromptSubmit: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatPromptSubmit.vue")['default']>
export const LazyB24ChatReasoning: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatReasoning.vue")['default']>
export const LazyB24ChatShimmer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatShimmer.vue")['default']>
export const LazyB24ChatTool: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ChatTool.vue")['default']>
export const LazyB24Checkbox: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']>
export const LazyB24CheckboxGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.vue")['default']>
export const LazyB24Chip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']>
export const LazyB24Collapsible: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']>
export const LazyB24ColorPicker: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.vue")['default']>
export const LazyB24CommandPalette: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.vue")['default']>
export const LazyB24Container: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']>
export const LazyB24ContextMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.vue")['default']>
export const LazyB24ContextMenuContent: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.vue")['default']>
export const LazyB24Countdown: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']>
export const LazyB24DashboardGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.vue")['default']>
export const LazyB24DashboardNavbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardNavbar.vue")['default']>
export const LazyB24DashboardPanel: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardPanel.vue")['default']>
export const LazyB24DashboardResizeHandle: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardResizeHandle.vue")['default']>
export const LazyB24DashboardSearch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.vue")['default']>
export const LazyB24DashboardSearchButton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.vue")['default']>
export const LazyB24DashboardSidebar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebar.vue")['default']>
export const LazyB24DashboardSidebarCollapse: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebarCollapse.vue")['default']>
export const LazyB24DashboardSidebarToggle: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSidebarToggle.vue")['default']>
export const LazyB24DashboardToolbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardToolbar.vue")['default']>
export const LazyB24DescriptionList: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']>
export const LazyB24Drawer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Drawer.vue")['default']>
export const LazyB24DropdownMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']>
export const LazyB24DropdownMenuContent: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']>
export const LazyB24Editor: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Editor.vue")['default']>
export const LazyB24EditorDragHandle: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorDragHandle.vue")['default']>
export const LazyB24EditorEmojiMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorEmojiMenu.vue")['default']>
export const LazyB24EditorMentionMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorMentionMenu.vue")['default']>
export const LazyB24EditorSuggestionMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorSuggestionMenu.vue")['default']>
export const LazyB24EditorToolbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/EditorToolbar.vue")['default']>
export const LazyB24Empty: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.vue")['default']>
export const LazyB24Error: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.vue")['default']>
export const LazyB24FieldGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.vue")['default']>
export const LazyB24FileUpload: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.vue")['default']>
export const LazyB24Footer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Footer.vue")['default']>
export const LazyB24FooterColumns: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FooterColumns.vue")['default']>
export const LazyB24Form: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']>
export const LazyB24FormField: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']>
export const LazyB24Header: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Header.vue")['default']>
export const LazyB24Input: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']>
export const LazyB24InputDate: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputDate.vue")['default']>
export const LazyB24InputMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']>
export const LazyB24InputNumber: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']>
export const LazyB24InputTags: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.vue")['default']>
export const LazyB24InputTime: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTime.vue")['default']>
export const LazyB24Kbd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']>
export const LazyB24Link: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']>
export const LazyB24LinkBase: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']>
export const LazyB24Main: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Main.vue")['default']>
export const LazyB24Modal: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']>
export const LazyB24ModalDialogClose: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']>
export const LazyB24Navbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']>
export const LazyB24NavbarDivider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']>
export const LazyB24NavbarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']>
export const LazyB24NavbarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']>
export const LazyB24NavigationMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']>
export const LazyB24OverlayProvider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']>
export const LazyB24Page: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Page.vue")['default']>
export const LazyB24PageAside: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageAside.vue")['default']>
export const LazyB24PageBody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageBody.vue")['default']>
export const LazyB24PageCard: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.vue")['default']>
export const LazyB24PageCardGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCardGroup.vue")['default']>
export const LazyB24PageColumns: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.vue")['default']>
export const LazyB24PageFeature: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageFeature.vue")['default']>
export const LazyB24PageGrid: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.vue")['default']>
export const LazyB24PageHeader: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageHeader.vue")['default']>
export const LazyB24PageLinks: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.vue")['default']>
export const LazyB24PageList: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.vue")['default']>
export const LazyB24PageSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageSection.vue")['default']>
export const LazyB24Pagination: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.vue")['default']>
export const LazyB24PinInput: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.vue")['default']>
export const LazyB24Popover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']>
export const LazyB24Progress: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']>
export const LazyB24RadioGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']>
export const LazyB24Range: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']>
export const LazyB24ScrollArea: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ScrollArea.vue")['default']>
export const LazyB24Select: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']>
export const LazyB24SelectMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']>
export const LazyB24Separator: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']>
export const LazyB24Sidebar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']>
export const LazyB24SidebarBody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']>
export const LazyB24SidebarFooter: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']>
export const LazyB24SidebarHeader: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']>
export const LazyB24SidebarHeading: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']>
export const LazyB24SidebarLayout: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']>
export const LazyB24SidebarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']>
export const LazyB24SidebarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']>
export const LazyB24Skeleton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']>
export const LazyB24Slideover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']>
export const LazyB24Stepper: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.vue")['default']>
export const LazyB24Switch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']>
export const LazyB24Table: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.vue")['default']>
export const LazyB24TableWrapper: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.vue")['default']>
export const LazyB24Tabs: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']>
export const LazyB24Textarea: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']>
export const LazyB24Theme: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Theme.vue")['default']>
export const LazyB24Timeline: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.vue")['default']>
export const LazyB24Toast: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']>
export const LazyB24Toaster: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']>
export const LazyB24Tooltip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']>
export const LazyB24User: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.vue")['default']>
export const LazyB24LocaleSelect: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
